// <auto-generated />
namespace MomWorld.DataContexts.Migrations.ArticleMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _6th : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_6th));
        
        string IMigrationMetadata.Id
        {
            get { return "201504040929595_6th"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
